/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swordfish.views;

import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author jrob
 */
public class LogIn extends javax.swing.JDialog {

    @SuppressWarnings("UseOfObsoleteCollectionType")
    private final Vector<JButton> butts = new Vector<JButton>();

    public LogIn(int[] pointer) {
        this.pointer = pointer;
        initComponents();
//        pack();
//        butts = new Vector();
        butts.add(b_cancel);
        butts.add(b_logon);
        butts.add(b_register);
        this.setResizable(false);
    }

    public LogIn(int[] pointer, Vector<JLabel> labs) {
        this.pointer = pointer;
        initComponents();
//        pack();
//        butts = new Vector();
        this.labs = labs;
        butts.add(b_cancel);
        butts.add(b_logon);
        butts.add(b_register);
        this.setResizable(false);
    }

    /**
     * Creates new form LogOn
     *
     * @param parent
     * @param modal
     */
    public LogIn(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        butts.add(b_cancel);
        butts.add(b_logon);
        butts.add(b_register);
    }

    public Vector<JButton> getButtons() {
        return butts;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_root = new javax.swing.JPanel();
        l_massID = new javax.swing.JLabel();
        l_password = new javax.swing.JLabel();
        tf_massID = new javax.swing.JTextField();
        tf_password = new javax.swing.JTextField();
        l_massDOT_logo = new javax.swing.JLabel();
        b_logon = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        b_register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        l_massID.setText("MassDOT ID:");

        l_password.setText("Password:");

        l_massDOT_logo.setIcon(new javax.swing.ImageIcon("/Users/jrob/capstoneECE/capstone/OCU/swordfish/resources/massDot_log_small.jpg")); // NOI18N

        b_logon.setText("Log-on");
        b_logon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_logonActionPerformed(evt);
            }
        });

        b_cancel.setText("Cancel");
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        b_register.setText("Register");
        b_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_registerActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout p_rootLayout = new org.jdesktop.layout.GroupLayout(p_root);
        p_root.setLayout(p_rootLayout);
        p_rootLayout.setHorizontalGroup(
                p_rootLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, p_rootLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(p_rootLayout.createSequentialGroup()
                                .add(0, 0, 0)
                                .add(b_logon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(3, 3, 3)
                                .add(b_cancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(3, 3, 3)
                                .add(b_register, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(p_rootLayout.createSequentialGroup()
                                .add(60, 60, 60)
                                .add(l_massDOT_logo)))
                .add(p_rootLayout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(p_rootLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(l_massID)
                                .add(l_password))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(p_rootLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(tf_massID, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .add(tf_password)))
        );
        p_rootLayout.setVerticalGroup(
                p_rootLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, p_rootLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(p_rootLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(l_massID)
                                .add(tf_massID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(3, 3, 3)
                        .add(p_rootLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(l_password)
                                .add(tf_password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(3, 3, 3)
                        .add(p_rootLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(b_cancel)
                                .add(b_logon)
                                .add(b_register))
                        .add(3, 3, 3)
                        .add(l_massDOT_logo))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(p_root, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(p_root, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_registerActionPerformed
        pointer[0] = 3;
    }//GEN-LAST:event_b_registerActionPerformed

    private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
        pointer[0] = 2;
        this.dispose();
    }//GEN-LAST:event_b_cancelActionPerformed

    private void b_logonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_logonActionPerformed
        pointer[0] = 1;
    }//GEN-LAST:event_b_logonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                final LogIn dialog = new LogIn(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
                        dialog.setVisible(false);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     *
     */
    int[] pointer = new int[1];

    private Vector<JLabel> labs;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_logon;
    private javax.swing.JButton b_register;
    private javax.swing.JLabel l_massDOT_logo;
    private javax.swing.JLabel l_massID;
    private javax.swing.JLabel l_password;
    private javax.swing.JPanel p_root;
    private javax.swing.JTextField tf_massID;
    private javax.swing.JTextField tf_password;
    // End of variables declaration//GEN-END:variables
}
